offline-message: '&cServer is offline!'
show-offline-message: true
interval: 5
timeout: 1500
cooldown: 2000

servers:
  hub:
    address: '192.99.1.39:25565'
    displayname: '&6AG Hub'

layouts:
  default:
    teleport: true
    layout:
      - '%displayname%'
      - ''
      - '%isonline%'
      - '&online%numpl%/%maxpl%'
    online: '&aOnline'
    offline: '&cOffline'
    offline-int: '-'