offline-message: '&cServer is offline!'
show-offline-message: true
interval: 5
sign-updates: 20
timeout: 1500
cooldown: 2000

servers:
  hub:
    address: '192.99.1.39:25565'
    displayname: '&6AG Hub'

layouts:
  default:
    teleport: true
    layout:
      - 'Join'
      - '%displayname%'
      - '%numpl%/%maxpl%'
      - '%isonline%'
    online: '&aOnline'
    offline: '&cOffline'
    offline-int: '-'
  info:
    teleport: false
    layout:
      - 'Archer Games'
      - '%displayname%'
      - '&c%numpl%&a/&c%maxpl%'
      - '%isonline%'
    online: '&aOnline'
    offline: '&cOffline'
    offline-int: '-'