offline-message: '&cServer is offline!'
show-offline-message: true
interval: 5
timeout: 1500
cooldown: 2000

servers:
  hub:
    displayname: '&5AG Hub'
  ag1:
    displayname: '&3AG 1'

layouts:
  default:
    teleport: true
    layout:
      - '%displayname%'
      - ''
      - '&online%players%'
      - '%status%'
    online: '&aOnline'
    offline: '&cOffline'
    offline-int: '-'