name: ${project.name}
author: LimeByte
version: ${project.version}
description: ${project.description}

main: ${project.groupId}.${project.artifactId}.ServerSigns
load: POSTWORLD

commands:
  serversigns:
    description: Various ServerSigns commands

permissions:
  serversigns.use:
    description: Use ServerSigns
    default: true
  serversigns.create:
    description: Create ServerSigns
    default: op
  serversigns.destroy:
    description: Destroy ServerSigns
    default: op
  serversigns.reload:
    description: Reload config from disk
    default: op
  serversigns.ping:
    description: Ping a server
    default: op